#!/bin/bash
result=${PWD##*/};

mkdir ~/cjhgosina/CS/${result}

cp -r ~/csky/${result}/*  ~/cjhgosina/CS/${result}/

cd ~/cjhgosina/cs/${result}/

rm *.md
rm deploy
rm temp


cd ~/cjhgosina


git add *
git commit -m "update from ${result}"
git push sae master:1

cd ~/csky/${result}/
git add *
git commit -m "update ${result} note"
